### ISSUE TITLE
When installing 1.1.0, error says "None of your spec sources contain a spec satisfying the dependency" occured

### ISSUE THREAD

**Issue by SeanChenU** [ActionKit/ActionKit#23] opened 2016-10-08 09:32 UTC
I am currently using 1.1.0.rc.2 of Cocoapods.

Error message:
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by SeanChenU** [comment] 2016-10-08 09:32
I tried pod repo update but the error still occurs.

**Comment by coolbnjmn** [comment] 2016-10-08 09:48
Hmm, there's likely a podspec update that needs to happen, since this was built against cocoapods 0.39 initially. I'll take a look at this shortly and update you here appropriately.

Thanks for reporting this!

**Comment by coolbnjmn** [comment] 2016-10-08 10:16
What version of xcode are you using? I just tried creating a new xcode8 project with ActionKit and had no issues. 

Could you show me your podfile, or at least the relevant part? I just tried this without issues.

**Comment by muzamilhassan1987** [comment] 2016-10-12 14:06
Hello,
I triend and getting same issue even after updating repo
I am using Xcode 7.3

**Comment by coolbnjmn** [comment] 2016-10-13 11:17
Hmm, I've now tried with both Xcode 7.3 and 8, for CocoaPods version 1.0.1 and am not able to reproduce this issue. Seems like this could be an issue linked to the beta version of CocoaPods.

**Comment by SeanChenU** [comment] 2016-10-16 09:49
I was trying to install ActionKit as instructed `pod 'ActionKit', '~> 1.1.0'` using 1.0.1 and received the error.

I believe the 1.1.0 version of ActionKit is not in the Cocoapods repo.
![2016-10-16 5 47 21](https://cloud.githubusercontent.com/assets/2536266/19416655/c7e9fe24-93c8-11e6-9e34-3700901bffd5.png)

**Comment by coolbnjmn** [comment] 2016-10-17 09:42
Oh wow, duh! Great catch...I've just updated the coocapods repo with the latest version. It's actually '1.2.0'. 

So `pod 'ActionKit', '~> 1.2.0'` should now work.

Thanks for the report, I'll close this as fixed, but please re-open if it doesn't work for you!

**Closed by coolbnjmn** 2016-10-17 09:42 UTC
